name: Build Huawei-Hisi970-HarmonyOS3.0-KSU-Kernel
on:
  workflow_dispatch:
  schedule:
     # Run once at 12:00 on Saturday. See http://crontab.guru
     - cron: '00 12 * * 6'
  push:
    branches:
      - HEAD
  pull_request:
      branches:
      - HEAD

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "4G"
      CCACHE_HARDLINK: "true"
      KERNEL_CMDLINE: "ARCH=arm64 CROSS_COMPILE=aarch64-linux-android- O=out"
    steps:
    

    - name: Install dependencies
      run: |
        sudo apt-get update -y 
        sudo apt install binutils make python2 libssl-dev flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev adb fastboot -y
        sudo apt install ccache -y
      
    
    - name: GetTime
      id: get_time
      run: |
        echo "TIME=$(TZ=UTC-8 date +%m%d%H%M )" >> $GITHUB_OUTPUT
  
    - name: Build Kernel
      run: |
         sudo ln -sf /usr/bin/python2.7 /usr/bin/python
         if [ -d include/config ];
          then
           echo "Find config,will remove it"
           rm -rf include/config
         else
          echo "No Config,good."
         fi

         export PATH=$(pwd)/clang-r346389c/bin/:$PATH
         export CLANG_PREBUILTS_PATH=$(pwd)/clang-r346389c/
         export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/clang-r346389c/lib64/
         export ARCH=arm64
         export SUBARCH=arm64
         make $KERNEL_CMDLINE merge_kirin970_defconfig
         make $KERNEL_CMDLINE -j$(nproc --all)
